---
# tasks file for ansible-role-apptainer

 - name: install apptainer
   package:
     name: "{{ item }}"
     state: installed
   with_items: "{{ apptainer_packages }}"
   when: apptainer_install_package|bool

 - name: template in apptainer.conf
   template:
     src: apptainer.conf.j2
     dest: "{{ apptainer_config_dir }}/apptainer.conf"
     backup: yes
     owner: root
     mode: 0644

 - name: template in init if apptainer_manage_init_file is True
   template:
     src: init.j2
     dest: "{{ apptainer_config_dir }}/init"
     backup: yes
     owner: root
     mode: 0644
   when: apptainer_manage_init_file|bool
